name: Concept SS
favicon: null
layout_spectrum: 0
typography_spectrum: 0.921
title: Concept SS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cfd4d8'
    - '#828c96'
    - '#9daebe'
    - '#18293b'
  brandStrength: 0.2508446464780718
  lightness: 0.8912356612272561
  saturation: 0.042395874159410596
  rhythmicContrast: 0.5173523693811148
purpose: []
