name: Concept SS
favicon: null
layout_spectrum: 0
typography_spectrum: 0.90751
title: Concept SS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cfd4d8'
    - '#828c96'
    - '#9daebe'
    - '#18293b'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
